_BASE_: "../Base-RCNN-FPN.yaml"
EXPERIMENT_NAME: "adapted_fast_r-CNN_R101"
DATASET_PATH: "/data/mostertrij/data/frcnn_images/uLB300_precomputed_removed/LGZ_COCOstyle/annotations/"
DATASETS:
  TRAIN: ("train",)
  TEST: ("train","val","test")
  IMAGE_DIR: "/data/mostertrij/data/frcnn_images/"
INPUT:
  ROTATION_ENABLED: True
  SCALE_FACTOR: 1.0
  MIN_SIZE_TRAIN: (200,)
  MIN_SIZE_TEST: 200
  MAX_SIZE_TRAIN: 200
  MAX_SIZE_TEST: 200
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  LOAD_PROPOSALS: True
  PROPOSAL_GENERATOR:
    NAME: "PrecomputedProposals"
  # Determine mean of our GBR channels
  PIXEL_MEAN: [246.76874, 239.2626,  249.68981] 
  PIXEL_STD: [12.0407, 8.531488, 10.88658]
  RESNETS:
    DEPTH: 101
  BACKBONE:
      # Remove StopGrad at a specified stage so that no bottom layers are frozen
      # Default value is 2
      FREEZE_AT: -1
  RPN:
    IOU_THRESHOLDS: [0.5, 0.8]
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512   # faster, and good enough for this toy dataset (default: 512)
    NUM_CLASSES: 1  # only has one class (radio_source)
    SCORE_THRESH_TEST: 0.0
    NMS_THRESH_TEST: 1.0
DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 1
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  BASE_LR: 0.0003
  IMS_PER_BATCH: 4
  STEPS: ()
  MAX_ITER: 50000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 10000
  #EXTRA_EVAL: [1,500,1000,2500,5000,10000,15000]
