_BASE_: "base_lofar_fast_rcnn.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/LB300_precomputed_removed_10/"
DATASET_PATH: "/data/mostertrij/data/frcnn_images/LB300_precomputed_removed/LGZ_COCOstyle/annotations/"
DATASETS:
  TEST: ("train","val","test")
  TRAIN_SIZE: 10
INPUT:
  ROTATION_ENABLED: True
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 300000
TEST:
  REMOVE_UNRESOLVED: True
  REMOVE_THRESHOLD: ("0.20")
  EVAL_PERIOD: 20000
