_BASE_: "base_lofar.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/inference_LB300_removed/"
DATASET_PATH: "/data/mostertrij/data/frcnn_images/inference_LB300_precomputed_removed/LGZ_COCOstyle/annotations/"
DATASETS:
  TRAIN: ("inference",)
  TEST: ("inference",)
  TRAIN_SIZE: 9999999999999999999
MODEL:
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.0
    NMS_THRESH_TEST: 1.0
INPUT:
  ROTATION_ENABLED: False
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 6000
  CHECKPOINT_PERIOD: 20000
TEST:
  REMOVE_UNRESOLVED: True
  REMOVE_THRESHOLD: ("0.20")
  EVAL_PERIOD: 20000
