_BASE_: "base_lofar_faster_rcnn_X101-FPN.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/uLB300_faster_X101_removed_withRot_constantLR/"
DATASETS:
  TRAIN: ("train",)
  TEST: ("train","val","test")
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 300000 
  CHECKPOINT_PERIOD: 30000
TEST:
  REMOVE_UNRESOLVED: True
  REMOVE_THRESHOLD: ("0.20") # Needs to be a string
  EVAL_PERIOD: 30000
  EXTRA_EVAL: [1000,5000,10000,20000,40000,50000]
