_BASE_: "base_lofar_fast_rcnn_R50-FPN.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/uLB300_fast_R50_pretrained_removed_withRot_constantLR/"
DATASETS:
  TRAIN: ("train",)
  TEST: ("train","val","test")
MODEL:
  #PRETRAINED_WEIGHTS: "/data/mostertrij/data/pretrained_models/pretrained_model_epochs500_batch256_gpus4_cjprob0.1_cjstr0.01_minscale0.6_gaus0.5_kernel2_normFalse.pth"
  PRETRAINED_WEIGHTS: "/data/mostertrij/data/pretrained_models/pretrained_model_epochs2500_batch64_gpus1_cjprob0.1_cjstr0.01_minscale0.6_gaus0.5_kernel2_normFalse.pth"
INPUT:
  ROTATION_ENABLED: True
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 100000 
  CHECKPOINT_PERIOD: 5000
TEST:
  REMOVE_UNRESOLVED: True
  REMOVE_THRESHOLD: ("0.20") # Needs to be a string
  EVAL_PERIOD: 10000
  EXTRA_EVAL: [1000,5000]
