_BASE_: "base_lofar_faster_rcnn_R50-FPN.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/uLB300_faster_R50_removed_withRot_constantLR_IOU/"
DATASETS:
  TRAIN: ("train",)
  TEST: ("train","val","test")
INPUT:
  ROTATION_ENABLED: True
MODEL:
  RPN:
    IOU_THRESHOLDS: [0.5, 0.8]
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 60000 
  CHECKPOINT_PERIOD: 5000
TEST:
  REMOVE_UNRESOLVED: True
  REMOVE_THRESHOLD: ("0.20") # Needs to be a string
  EVAL_PERIOD: 10000
  EXTRA_EVAL: [1000,5000]
