_BASE_: "base_lofar_fast_rcnn_R50-FPN.yaml"
DATASET_PATH: "/data/mostertrij/data/frcnn_images/uLF300_precomputed_removed/LGZ_COCOstyle/annotations/"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/uLF300_fast_R50_removed_withRot_constantLR/"
DATASETS:
  TRAIN: ("test",)
  TEST: ("test",)
INPUT:
  ROTATION_ENABLED: True
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 50000 
  CHECKPOINT_PERIOD: 5000
TEST:
  REMOVE_UNRESOLVED: True
  REMOVE_THRESHOLD: ("0.20") # Needs to be a string
  EVAL_PERIOD: 10000
